#!/bin/bash
#
# 個人理財助理 — Claude Code Plugin Installer
#
# Usage: ./install.sh [--output-dir <path>] [--auto-permissions]
#
# This script installs the stock analysis plugin so it can be used
# from ANY directory in Claude Code. Just type "分析台積電" anywhere.
#

set -e

SKILLS_DIR="$HOME/.claude/skills"
OUTPUT_DIR="$HOME/stock-reports"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$HOME/.claude/stock-analysis.conf"
SETTINGS_FILE="$HOME/.claude/settings.json"
AUTO_PERMISSIONS=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --auto-permissions)
      AUTO_PERMISSIONS=true
      shift
      ;;
    --help|-h)
      echo "Usage: ./install.sh [--output-dir <path>] [--auto-permissions]"
      echo ""
      echo "Options:"
      echo "  --output-dir        Custom output directory for reports (default: ~/stock-reports)"
      echo "  --auto-permissions  Skip permission prompt, auto-configure Claude Code permissions"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Resolve to absolute path
OUTPUT_DIR="$(cd "$(dirname "$OUTPUT_DIR")" 2>/dev/null && pwd)/$(basename "$OUTPUT_DIR")" 2>/dev/null || OUTPUT_DIR="$HOME/stock-reports"

SKILLS=(
  "stock-orchestrator"
  "stock-data-fetcher"
  "stock-data-validator"
  "stock-financial-analyst"
  "stock-technical-analyst"
  "stock-quant-analyst"
  "stock-industry-macro"
  "stock-news-sentiment"
  "stock-institutional-flow"
  "stock-integrator"
  "stock-dashboard"
  "shared"
)

echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║    個人理財助理 — Claude Code Plugin      ║"
echo "╚═══════════════════════════════════════════════╝"
echo ""
echo "  Skills directory : $SKILLS_DIR"
echo "  Output directory : $OUTPUT_DIR"
echo ""

# Step 1: Create directories
mkdir -p "$SKILLS_DIR"
mkdir -p "$OUTPUT_DIR"

# Step 2: Install Python dependencies
echo "📦 Installing Python dependencies..."
python3 -m pip install -r "$SCRIPT_DIR/requirements.txt" --quiet 2>/dev/null || \
  pip install -r "$SCRIPT_DIR/requirements.txt" --quiet
echo "   ✓ Python dependencies installed"
echo ""

# Step 3: Copy skill directories & replace path placeholders
echo "🔧 Installing skills..."
for skill in "${SKILLS[@]}"; do
  if [ -d "$SCRIPT_DIR/$skill" ]; then
    # Clean previous install
    rm -rf "$SKILLS_DIR/$skill"
    # Copy fresh from source
    cp -r "$SCRIPT_DIR/$skill" "$SKILLS_DIR/$skill"
    # Replace placeholders in SKILL.md with absolute paths
    if [ -f "$SKILLS_DIR/$skill/SKILL.md" ]; then
      sed "s|{{SKILLS_DIR}}|$SKILLS_DIR|g; s|{{OUTPUT_DIR}}|$OUTPUT_DIR|g" \
        "$SKILLS_DIR/$skill/SKILL.md" > "$SKILLS_DIR/$skill/SKILL.md.tmp" && \
        mv "$SKILLS_DIR/$skill/SKILL.md.tmp" "$SKILLS_DIR/$skill/SKILL.md"
    fi
    echo "   ✓ $skill"
  else
    echo "   ✗ $skill (not found, skipping)"
  fi
done

# Remove __pycache__ from installed skills
find "$SKILLS_DIR" -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true

# Step 4: Write config file
cat > "$CONFIG_FILE" << EOF
# 個人理財助理 — Configuration
# Generated by install.sh on $(date)
#
# To change output directory, re-run:
#   ./install.sh --output-dir /your/custom/path

STOCK_ANALYSIS_SKILLS_DIR=$SKILLS_DIR
STOCK_ANALYSIS_OUTPUT_DIR=$OUTPUT_DIR
INSTALLED_FROM=$SCRIPT_DIR
PERMISSIONS_CONFIGURED=false
EOF
echo ""
echo "   ✓ Config saved to $CONFIG_FILE"

# Step 5: Configure Claude Code permissions (ask once)
configure_permissions() {
  echo ""
  echo "🔐 Configuring Claude Code permissions..."

  # Build the permissions JSON array that this plugin needs
  # Uses python3 to safely merge into existing settings.json
  python3 << 'PYEOF'
import json, sys, os

settings_file = os.path.expanduser("~/.claude/settings.json")
output_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/stock-reports")
skills_dir = os.path.expanduser("~/.claude/skills")

# Permissions required by this plugin
PLUGIN_PERMISSIONS = [
    # --- Read skills & config ---
    f"Read(//{skills_dir}/**)",
    # --- WebSearch (sentiment agent) ---
    "WebSearch",
    # --- WebFetch: Taiwan financial news ---
    "WebFetch(domain:tw.stock.yahoo.com)",
    "WebFetch(domain:finance.yahoo.com)",
    "WebFetch(domain:news.google.com)",
    "WebFetch(domain:www.businesstoday.com.tw)",
    "WebFetch(domain:www.chinatimes.com)",
    "WebFetch(domain:udn.com)",
    "WebFetch(domain:money.udn.com)",
    "WebFetch(domain:ec.ltn.com.tw)",
    "WebFetch(domain:www.moneydj.com)",
    "WebFetch(domain:www.cnyes.com)",
    "WebFetch(domain:technews.tw)",
    # --- WebFetch: International financial news ---
    "WebFetch(domain:www.reuters.com)",
    "WebFetch(domain:www.bloomberg.com)",
    "WebFetch(domain:www.cnbc.com)",
    "WebFetch(domain:seekingalpha.com)",
    "WebFetch(domain:www.marketwatch.com)",
    # --- Bash: plugin scripts (any ticker) ---
    f"Bash(mkdir -p {output_dir}/*)",
    f"Bash(python {skills_dir}/stock-data-fetcher/scripts/*)",
    f"Bash(python {skills_dir}/stock-data-validator/scripts/*)",
    f"Bash(python {skills_dir}/stock-quant-analyst/scripts/*)",
    f"Bash(python {skills_dir}/stock-integrator/scripts/*)",
    f"Bash(python {skills_dir}/stock-dashboard/scripts/*)",
    f"Bash(open {output_dir}/*)",
    # --- Bash: orchestrator runtime commands ---
    f"Bash(TODAY=*)",                            # Cache check (Step 1.5, 3.8)
    f"Bash(python3 -c *)",                       # Ad-hoc JSON extraction from validated_data
    f"Bash(cat {output_dir}/*)",                  # Read output files
]

# A marker so uninstall.sh can identify and remove these
MARKER = "# __stock-analysis-plugin__"

# Load existing settings or create new
settings = {}
if os.path.exists(settings_file):
    try:
        with open(settings_file, "r", encoding="utf-8") as f:
            settings = json.load(f)
    except (json.JSONDecodeError, IOError):
        settings = {}

perms = settings.setdefault("permissions", {})
allow_list = perms.setdefault("allow", [])
additional_dirs = perms.setdefault("additionalDirectories", [])

# Remove any previously installed plugin permissions (idempotent reinstall)
allow_list = [p for p in allow_list if not p.endswith(MARKER)]

# Add plugin permissions with marker
for p in PLUGIN_PERMISSIONS:
    tagged = f"{p} {MARKER}"
    if tagged not in allow_list:
        allow_list.append(tagged)

# Add output directory
if output_dir not in additional_dirs:
    additional_dirs.append(output_dir)

perms["allow"] = allow_list
perms["additionalDirectories"] = additional_dirs
settings["permissions"] = perms

# Write back
os.makedirs(os.path.dirname(settings_file), exist_ok=True)
with open(settings_file, "w", encoding="utf-8") as f:
    json.dump(settings, f, indent=2, ensure_ascii=False)
    f.write("\n")

print(f"   ✓ {len(PLUGIN_PERMISSIONS)} permissions configured in settings.json")
print(f"   ✓ Output directory added: {output_dir}")
PYEOF

  # Update config to record that permissions were configured
  sed -i.bak 's/PERMISSIONS_CONFIGURED=false/PERMISSIONS_CONFIGURED=true/' "$CONFIG_FILE" 2>/dev/null || \
    sed -i '' 's/PERMISSIONS_CONFIGURED=false/PERMISSIONS_CONFIGURED=true/' "$CONFIG_FILE"
  rm -f "$CONFIG_FILE.bak"
}

if [ "$AUTO_PERMISSIONS" = true ]; then
  configure_permissions
else
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "  🔐 Permission Configuration (one-time setup)"
  echo ""
  echo "  This plugin needs the following permissions to"
  echo "  run without manual approval every time:"
  echo ""
  echo "  • WebSearch — search for stock news"
  echo "  • WebFetch  — read financial news websites"
  echo "    (Yahoo Finance, Bloomberg, Reuters, etc.)"
  echo "  • Bash      — run Python analysis scripts"
  echo "    (limited to plugin scripts & report dirs only)"
  echo ""
  echo "  These permissions are READ-ONLY and scoped to"
  echo "  specific domains and file paths. No data is"
  echo "  uploaded or sent anywhere."
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  read -r -p "  Auto-configure permissions? [Y/n] " response
  case "$response" in
    [nN]|[nN][oO])
      echo ""
      echo "   ⏭  Skipped. You'll be prompted for each action in Claude Code."
      echo "      Re-run with --auto-permissions to configure later."
      ;;
    *)
      configure_permissions
      ;;
  esac
fi

# Step 6: Done
echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "  ✅ Installation complete!"
echo ""
echo "  Open Claude Code in ANY directory and try:"
echo "    分析台積電"
echo "    analyze AAPL"
echo "    台積電本益比多少     (quick answer)"
echo "    鴻海的財務狀況       (selective analysis)"
echo ""
echo "  Reports will be saved to:"
echo "    $OUTPUT_DIR/{stock_name}/"
echo ""
echo "  To uninstall:"
echo "    ./uninstall.sh"
echo ""
echo "═══════════════════════════════════════════════"
